### ISSUE TITLE
ReportPro2 problem with export to pdf with certain fonts

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1011]
Try to export to pdf in RP2 with this report:

[GS-fixed.zip](https://github.com/X-Sharp/XSharpPublic/files/8505072/GS-fixed.zip)

it leads to a System.OutOfMemoryException runtime exception:

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at XSharp.FixedMemory.Alloc(UInt32 nGroup, UInt32 nSize)
   at XSharp.RT.Functions.MemAlloc(UInt32 wBytes)
   at ReportPro2.rpTTFCMapFormat4.Load(rpTTFReader rdr) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\TTFSupport.prg:line 141
   at ReportPro2.rpTTFCMap.Load(rpTTFReader rdr) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\TTFSupport.prg:line 40
   at ReportPro2.rpTTFFont.ReadTables() in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\TTFFont.prg:line 256
   at ReportPro2.rpTTFFont..ctor(rpTTFReader oRdr, rpPdfCollection oDirectories) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\TTFFont.prg:line 160
   at ReportPro2.RpPdfFont.LoadTTF(String cName) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\Font.prg:line 138
   at ReportPro2.RpPdfFont..ctor(RpPdfDocument oDoc, Void* hFont, RpPdfFontFamily oFamily, String cStyle, String cName) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\Font.prg:line 121
   at ReportPro2.RpPdfFontFamily.AddStyle(Void* hFont, String cStyle, String cName) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\FontFamily.prg:line 18
   at ReportPro2.RpPdfDocument.AddTTFFont(Void* hFont, String cFamily, String cStyle, String cName) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\Document.prg:line 223
   at ReportPro2.RpPdfDocument._setfont(Void* hFont, String cFamily, String cStyle, Double lSize, Int32 nRotation) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\Document.prg:line 185
   at ReportPro2.RpPdfDocument.SetFont(Void* hFont, String cfamily, String cStyle, Double lSize, Int32 nRotation) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF\Document.prg:line 549
   at ReportPro2.rpPDFExport.SetFont(Void* hFont) in C:\ReportPro\Rp2Net\ReportPro2, Export\PDF Classes.prg:line 401
   at ReportPro2_Runtime.Functions._rpMFExportCallback(Void* hMemDC, _WINHANDLETABLE* lpHTable, _WINEMRUNION* lpMFR, Int32 nCount, Void* lpClientData) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDev (R,S,D).prg:line 4015
```

The problem is with the font used, "@Yu Gothic". When trying to read it through rpTTFCMapFormat4:Load() in \ReportPro2, Export\PDF\TTFSupport.prg, line 115:

```
METHOD Load(rdr AS rpTTFReader) AS VOID
    LOCAL segCount AS DWORD
    LOCAL glyphscount AS DWORD
    LOCAL i AS DWORD
    local wGlyph as WORD

    // format
    rdr:ReadUShort()
    SELF:Length := rdr:ReadUShort()
    // version
    rdr:ReadUShort()
    SELF:SegCountX2 :=rdr:ReadUShort()
    //rdr:Position += 6
    rdr:ReadUShort()
    rdr:ReadUShort()
    rdr:ReadUShort()
    segCount        := SELF:SegCountX2 /2
    glyphscount     := (SELF:Length - (16 + 8 * segCount)) /2
    IF (SELF:EndCount != NULL_PTR)
        SELF:Destroy()
    ENDIF
    SELF:EndCount    := MemAlloc( segCount * _SIZEOF(WORD))
    SELF:StartCount  := MemAlloc( segCount * _SIZEOF(WORD))
    SELF:IdDelta     := MemAlloc( segCount * _SIZEOF(WORD))
    SELF:IdRangeOffs := MemAlloc( segCount * _SIZEOF(WORD))
    IF glyphscount > 0
        SELF:GlyphIdArray := MemAlloc(glyphscount * _SIZEOF(WORD))

```

the code "SELF:Length := rdr:ReadUShort()" results to a zero value for SELF:Length, which afterwards overflows when caclulating glyphscount, which results to a huge amount of memory to be allocated, which throws the exception. Same problem exists not only with this font, but with some others, too, like the "Colibri" font. Using instead of those fonts for example "Arial", makes the problem go away. Also RP3 works with this font with no problems.

**Comment by RobertvanderHulst** [comment]
Chris I have merged Bernhards changes. Can you verify that this works?

**Comment by cpyrgas** [comment]
Yeap, looks very good!!

**Comment by cpyrgas** [comment]
Bernhard, I have run your test report against our new reporting engine, and it seems to work well. Can you please check if the pdf export it produces is what you expect it to be?

[VVK_Karte_SKO - fixed.pdf](https://github.com/user-attachments/files/30334216/VVK_Karte_SKO.-.fixed.pdf)
