### ISSUE TITLE
System.AccessViolationException in the initialization code of VOGUIClasses.dll

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1177]
_Unhandled exception: System.AccessViolationException: An attempt was made to read or write to the protected memory. This is often an indication that other that other memory is corrupted._

Yesterday in the evening everything worked! I just don't get what happened. Nothing has changed! I've installed 2.14 two days ago, have all the apps rebuilt several times - they were all working. But not today.
The exception occurs before the entry-point of the application at this callstack:
  
 at XSharp.FixedMemory.Alloc(UInt32 nGroup, UInt32 nSize)
   at XSharp.RT.Functions.String2Mem(String s)
   at XSharp.Internal.CompilerServices.String2Psz(String s, List`1 pszList)
   at VOGUIClasses.Functions.__InitFunctionPointer()
   at VOGUIClasses.Functions.$Init3()
   at $AppInit()

It is somewhere here:
![image](https://user-images.githubusercontent.com/9467830/202896298-dd634401-44ea-47bc-b79e-053ce3ac3917.png)

And if I use debug version of X# libraries, there is no problem.

**Comment by Serggio** [comment]
![2022-11-20_15-15-00](https://user-images.githubusercontent.com/9467830/202901470-6f1a0d53-ebbd-489e-8aac-20bca168626d.png)

There is a difference between debug and redistributale versions of the same library.

**Comment by Serggio** [comment]
It seems to be just a compiler optimization. Well, I still don't know what is wrong.

**Comment by Serggio** [comment]
Fixed in 2.14.0.1. Should I close this issue?
