### ISSUE TITLE
ReportPro 2 exception when exporting to PDF

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#125]
LeigProman reported:
Whilst on ReportPro - something that came up today trying to export a report >100 pages to PDF:

The following error was encountered while fetching the next logical record:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
at ReportPro2.frmProgress.SetPageNo(Int32 nPage)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at VulcanRTFuncs.Functions.$LateBinding$__SendHelper(Object oObject, String cName, __Usual[] args, __Usual& retval)
at VulcanRTFuncs.Functions.__InternalSend(__Usual oObject, String cName, __Usual[] args)
at ReportPro2.PtrDevice._StartPage()
at ReportPro2.PtrDevice._CollectPage()
at ReportPro2.PtrDevice._CollectExportPages()

**Comment by RobertvanderHulst** [comment]
Fixed in commit 3102306a37a973a350ba933d358a82e15944b4e7
