### ISSUE TITLE
VS editor exception

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1279]
Got the following exception. I had copied/pasted in the editor (in the first line) this code:

```
LOCAL i AS INT
LOCAL s := "test" AS STRING
LOCAL CONST STEP_VAL := 2 AS INT

FOR i := 1 UPTO s:Length STEP STEP_VAL
NEXT
```

then put the caret in the first line, pressed ENTER to move all the code one line down and in the now empty first line I typed

`FUNCTION aaa(`

The error happened the moment I typed the opening paren.

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: positionat Microsoft.VisualStudio.Text.SnapshotPoint..ctor(ITextSnapshot snapshot, Int32 position)
at XSharp.LanguageService.XSharpSignatureHelpCommandHandler.cursorAfterOpenToken() in C:\XSharp\DevPublic\VisualStudio\LanguageService\Parameter Info\SignatureCommandHandler.cs:line 248
at XSharp.LanguageService.XSharpSignatureHelpCommandHandler.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Parameter Info\SignatureCommandHandler.cs:line 162
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at XSharp.LanguageService.XSharpEditorCommandHandler.<>c__DisplayClass11_0.<<Exec>b__0>d.MoveNext() in C:\XSharp\DevPublic\VisualStudio\LanguageService\Generic\EditorCommandHandler.cs:line 77 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at XSharp.LanguageService.XSharpEditorCommandHandler.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Generic\EditorCommandHandler.cs:line 73
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by RobertvanderHulst** [comment]
You will not see the problem if you enable the option "Brace Completion".
![image](https://github.com/X-Sharp/XSharpPublic/assets/14240939/c6c490ca-0d1c-4b13-88be-83a82d1a410c)

**Comment by cpyrgas** [comment]
> You will not see the problem if you enable the option "Brace Completion". ![image](https://user-images.githubusercontent.com/14240939/245065533-c6c490ca-0d1c-4b13-88be-83a82d1a410c.png)

Actually I have the option enabled! Basically all options are checked.

**Comment by cpyrgas** [comment]
Confirmed fixed
