### ISSUE TITLE
Macro compiler problem with user defined functions

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#130]
In some cases, the macro compiler throws a "error XM0209: Ambiguous call" when macro compiling an expression with a user (re) defined function.

```
FUNCTION Start() AS VOID
? &("AllTrim('asd')")   // OK
? &("Left('asd' , 1)")  // error XM0209: Ambiguous call
RETURN
```

Unhandled Exception: XSharp.MacroCompiler.CompilationError: (1,1): error XM0209:
 Ambiguous call
   at XSharp.Runtime.MacroCompiler.Compile(String macro, Boolean lAllowSingleQuo
tes, Module module, Boolean& isCodeblock, Boolean& addsMemVars)
   at XSharp.RT.Functions.MCompile(String cMacro, Boolean lAllowSingleQuotes)
   at XSharp.RT.Functions.Evaluate(String cExpression, Boolean lAllowSingleQuote
s)
   at XSharp.RT.Functions.Evaluate(String cExpression)
   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\x
Runtime\Prg\xRntime.prg:line 3

[XSharpMacroCompilerFunctions.zip](https://github.com/X-Sharp/XSharpPublic/files/3501888/XSharpMacroCompilerFunctions.zip)

**Comment by RobertvanderHulst** [comment]
In VO the overload for "Left" will never be called. The VO macro compiler handles some functions "differently", so even when they are strongly typed they can still be called from macros.

**Comment by cpyrgas** [comment]
Robert, this had been very widely used in vulcan though,
