### ISSUE TITLE
Internal Compiler Error with duplicate declaring of fields/memvars 

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1475]
Following produces an ICE, should report compiler errors of course.

```
//memvar+
MEMVAR Foo
PUBLIC Foo

FIELD Bar
MEMVAR Bar

MEMVAR Test
MEMVAR Test

FIELD Another
FIELD Another


FUNCTION Start() AS VOID
```

```
error XS9999: An internal compiler error has occurred: 'An item with the same key has already been added.',    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.EnterFilewidevar(FilewidevarContext context)
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.FilewidevarContext.EnterRule(IParseTreeListener listener)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore()
```

**Comment by cpyrgas** [comment]
Confirmed fixed
