### ISSUE TITLE
ReportPro2 corrupts .rpt files

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#148]
Open the attached report with the X# version of RP2, it opens fine and can print etc. Save As a different file (with no other changes), then close and re-open the new file, it fails with an exception in PtrDevice:ImportCfg()

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> XSharp.Internal.WrappedException: Exception of type 'XSharp.Internal.WrappedException' was thrown.

   at ReportPro2_Runtime.Functions.rpErrorHandler(Error oError) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Forms\Error - Code (R,S,D).prg:line 171

   at ReportPro2_Runtime.Functions.<>c.<_InitErrorHandler>b__19_0(__Usual oError) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Forms\Error - Code (R,S,D).prg:line 24

   at <>f__AnonymousType0.Eval(__Usual[] args)

   at XSharp.RT.Functions.Eval(ICodeblock block, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\Codeblock.prg:line 24

   at ReportPro2.PtrDevice.ImportCfg(String cId, Void* hFile) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDev (R,S,D).prg:line 2814

   at ReportPro2.RpReportDesigner.ReadReport(__Array aDbfSwap) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Support\File Read (R,S,D).prg:line 88

   at ReportPro2.RpReportDesigner._InitReadRpt(String cFileName) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Report\RpReportDesigner.prg:line 99

   at ReportPro2.RpReportDesigner.LoadRpt(String cFileName) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Report\RpReportDesigner.prg:line 594

   at ReportPro2.rpShellWindow.OpenRptFile(String cFile) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Forms\MDI Shell.prg:line 317

   at ReportPro2.rpShellWindow.OpenReport(__Usual[] Xs$Args) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Forms\MDI Shell.prg:line 304

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at OOPHelpers.SendHelper(Object oObject, MethodInfo mi, __Usual[] uArgs, __Usual& result) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 615

   at OOPHelpers.SendHelper(Object oObject, String cMethod, __Usual[] uArgs, __Usual& result) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 608

   at OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 651

   at XSharp.RT.Functions.__InternalSend(__Usual oObject, String cMethod, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 1207

   at ReportPro2.RpReportDesigner.Menu_OpenReport() in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Menus\RP Menu - Code (D).prg:line 131

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at OOPHelpers.SendHelper(Object oObject, MethodInfo mi, __Usual[] uArgs, __Usual& result) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 618

   at OOPHelpers.SendHelper(Object oObject, String cMethod, __Usual[] uArgs, __Usual& result) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 608

   at OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 651

   at XSharp.RT.Functions.Send(__Usual o, __Usual uMethod, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 1189

   at VO.Window.__CommandFromEvent(Object oEvent) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\Window.prg:line 421

   at VO.Window.__PreMenuCommand(Event oMenuCommandEvent) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\Window.prg:line 896

   at VO.Window.Dispatch(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\Dispatch.prg:line 392

   at VO.AppWindow.Dispatch(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\Application Window.prg:line 149

   at ReportPro2.RpReportDesigner.Dispatch(__Usual[] Xs$Args) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Report\RpReportDesigner.prg:line 470

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

   at OOPHelpers.SendHelper(Object oObject, MethodInfo mi, __Usual[] uArgs, __Usual& result) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 615

   at OOPHelpers.SendHelper(Object oObject, String cMethod, __Usual[] uArgs, __Usual& result) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 608

   at OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 651

   at XSharp.RT.Functions.__InternalSend(__Usual oObject, String cMethod, __Usual[] args) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\OOP.prg:line 1207

   at VO.__DocApp.Dispatch(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\DocApp.prg:line 89

   at VOGUIClasses.Functions.__WCDocAppWndProc(Void* hWnd, UInt32 uMsg, UInt32 wParam, Int32 lParam) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\DocApp.prg:line 203

   at VOWin32APILibrary.Functions.SendMessage(Void* hwnd, UInt32 Msg, UInt32 wParam, Int32 lParam)

   at VO.ShellWindow.Dispatch(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\ShellWindow.prg:line 313

   at ReportPro2.rpShellWindow.Dispatch(__Usual[] Xs$Args) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Forms\MDI Shell.prg:line 174

   at VOGUIClasses.Functions.__WCShellWndProc(Void* hWnd, UInt32 uMsg, UInt32 wParam, Int32 lParam) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\ShellWindow.prg:line 669

   at VOWin32APILibrary.Functions.DispatchMessage(_winMSG* lpMsg)

   at VO.App.Exec(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\VOSDK\Source\VOSDK\GUI_Classes_SDK\Application.prg:line 194

   at ReportPro.ReportPro2App.Start(String[] aArgs) in C:\ReportPro\Rp2Net\ReportPro2\Start.prg:line 33

   at ReportPro2.Exe.Functions.Start(String[] aArgs) in C:\ReportPro\Rp2Net\ReportPro2\Start.prg:line 13

[test_rpt.zip](https://github.com/X-Sharp/XSharpPublic/files/3538165/test_rpt.zip)

**Comment by RobertvanderHulst** [comment]
That problem should be fixed with the updated ZIP on the X# website (where ReportPro2.exe and some of the other files are dated Aug 20,2019)

**Comment by cpyrgas** [comment]
Ah OK thanks. Was the change just not pushed to source control?

**Comment by RobertvanderHulst** [comment]
Chris,
I had pushed it to the main branch. Did not merge that back into the dev branch. I now did.
Sorry about that.
