### ISSUE TITLE
Windows Forms Designer : Crashes when editing a VFPXPorter generated Form - 2nd Sample... Crashes without errors

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#1596]
**Describe the bug**
Same as  #1595, but with a more complex VFP Application.
I'm using X# 2.21

**To Reproduce**
It reproduces with my full app ;)

I've tried to track it in VSIntegration solution and the VS Experimental instance, but as it is using the registered CodeDomProvider...It's hard to check.

Anyway, I was able to get this error log :
Exception thrown: 'System.ArgumentOutOfRangeException' in mscorlib.dll
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at XSharp.CodeDom.ParseHelpers.GetLeadingTrivia(ParserRuleContext context, IList`1 tokens) in C:\XSharp\DevPublic\src\VisualStudio\CodeDomProvider\XSharpTreeDiscoverClass.cs:line 768
   at XSharp.CodeDom.XSharpBaseDiscover.writeTrivia(CodeObject o, XSharpParserRuleContext context, Boolean end) in C:\XSharp\DevPublic\src\VisualStudio\CodeDomProvider\XSharpTreeDiscoverBase.cs:line 1920
   at XSharp.CodeDom.XSharpBaseDiscover.EnterUsing_(Using_Context context) in C:\XSharp\DevPublic\src\VisualStudio\CodeDomProvider\XSharpTreeDiscoverBase.cs:line 1906
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.Using_Context.EnterRule(IParseTreeListener listener)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at XSharp.CodeDom.XSharpCodeParser.Parse(String source) in C:\XSharp\DevPublic\src\VisualStudio\CodeDomProvider\XSharpCodeParser.cs:line 126

**Comment by RobertvanderHulst** [comment]
I'll look into this asap.
Btw: you can simply delete the CodeDomprovider from the GAC to debug it. 
The version in the GAC is only needed to generate code behind for WPF projects, which is done from a build task.

**Comment by FabForay** [comment]
After running the experimental VS instance, I was able to reproduce the error.
In XSharpTreeDiscoverBase, line 1920, it calls GetLeadingTrivia().
Then it goes into XSharpTreeDiscoverClass, line 763.
There OriginalTokenIndex returns 18, where the length of the tokens  if 17, and the max pos is 16...so the crash.
There is something wrong in the Context.

I attach  a zip with the offending solution.

Open the SLN, try to open the  file toolbar_navig.prg in the ClassLibraries project, folder Libs/toolbar.
[MyDemo.zip](https://github.com/user-attachments/files/17356876/MyDemo.zip)

**Comment by RobertvanderHulst** [comment]
Fabrice,
I'll try to look into this in Munich on Tuesday or Wednesday, so you will have a fix for your session.

**Comment by RobertvanderHulst** [comment]
The problem seems to be that it is looking in the tokens of the imported file VFPXPorter.xh  and not the tokens of the form.

**Comment by RobertvanderHulst** [comment]
Ok, found it. The problem is the `USING toolbar` in the header file.
This becomes the first entity in the parsetree. When trying to load the tokens of the tree, we fetch the tokens based on the start token of the parsetree. The first element in the parsetree is this `USING toolbar` that is from the header file.
I will change the logic to exclude entities from header files when determining the first token. That should fix this.

**Comment by fforay** [comment]
Many thanks, it solves my trouble. 
You always guide and inspire 😁

I can now close both tickets

**Comment by RobertvanderHulst** [comment]
Keep the music alive !

**Comment by cpyrgas** [comment]
Confirmed fixed
