### ISSUE TITLE
Compiler crash with default values

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1647]
All of the function definitions below cause an ICE (in non-core dialects) instead of a proper error message:

```
// VO dialect
FUNCTION TestFunc1( a AS INT, b := 85, c AS INT) AS VOID STRICT
FUNCTION TestFunc2( a AS INT, b := 85, c := 1 AS INT) AS VOID STRICT
FUNCTION TestFunc3( b := 85, c AS INT) AS VOID STRICT
FUNCTION TestFunc4( b := 85, c := 1 AS INT) AS VOID STRICT

error XS9999: An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.GreenNode.AdjustFlagsAndWidth(GreenNode node)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.CastExpressionSyntax..ctor(SyntaxKind kind, SyntaxToken openParenToken, TypeSyntax type, SyntaxToken closeParenToken, ExpressionSyntax expression, SyntaxFactoryContext context)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.EncodeDefaultParameter(ExpressionContext initexpr, DatatypeContext datatype)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.ExitParameter(ParameterContext context)
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.ParameterContext.ExitRule(IParseTreeListener listener)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore()
```

**Comment by cpyrgas** [comment]
Confirmed fixed
