### ISSUE TITLE
Internacl compiler error with preprocessor directive

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#165]
Following results to a error XS9999: An internal compiler error has occurred: 'Index was out of range. '
The intention of the directive was to "do nothing"
In any case, there should not be an ICE

```
#xcommand ABC DEF [<msg>] =>  

FUNCTION Start() AS VOID
  ABC DEF "abc"	
RETURN
```

C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(1,1): error XS9999: An internal compiler error has occurred: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index',    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.PPRuleDictionary.FindMatchingRule(IList`1 tokens, PPMatchRange[]& matchInfo) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Preprocessor\XSharpPPHelpers.cs:line 137
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpPreprocessor.doProcessCommands(IList`1 line, IList`1& result) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Preprocessor\XSharpPreprocessor.cs:line 1836
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpPreprocessor.doNormalLine(IList`1 line, Boolean write2PPO) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Preprocessor\XSharpPreprocessor.cs:line 1626
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpPreprocessor.ProcessLine(IList`1 line) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Preprocessor\XSharpPreprocessor.cs:line 607
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpPreprocessor.PreProcess() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Preprocessor\XSharpPreprocessor.cs:line 511
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpLanguageParser.cs:line 241

**Comment by RobertvanderHulst** [comment]
I am glad that I have added the try catches in the compiler, so this at least produces a message with a callstack !
