### ISSUE TITLE
"Ambiguous call" macro compiler error with overloaded methods

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#179]
The following results to an error XM0209, not that FUNCTION Space(x) has one overload that accepts an INT and another accepting a DWORD

FUNCTION Start() AS VOID
? &("{|x|Space(x)}") // error XM0209: Ambiguous call

// those are ok:
? &("{|x| Left('asd' , x)}")
? &("{|x| Left(x , 3)}")
? &("{|x| Left(x , x)}")
RETURN

Unhandled Exception: XSharp.MacroCompiler.CompilationError: (1,5): error XM0209: Ambiguous call
   at XSharp.Runtime.MacroCompiler.Compile(String macro, Boolean lAllowSingleQuotes, Module module, Boolean& isCodeblock, Boolean& addsMemVars) in C:\xSharp\DevRt\Runtime\MacroCompiler\Compiler\MacroCompiler.cs:line 48
   at XSharp.RT.Functions.MCompile(String cMacro, Boolean lAllowSingleQuotes) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\Macro.prg:line 79
   at XSharp.RT.Functions.Evaluate(String cExpression, Boolean lAllowSingleQuotes) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\Macro.prg:line 33
   at XSharp.RT.Functions.Evaluate(String cExpression) in C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\Macro.prg:line 20
   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg:line 2

**Comment by RobertvanderHulst** [comment]
Chris,
What do you think. Shall we drop the Space() function with the Int32 argument ?

**Comment by cpyrgas** [comment]
Yes, I think so, there are other ways to deal with the INT/DWORD thing, like using the /vo4 compiler option.
