### ISSUE TITLE
VS activity log with error

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#215]
From Otto:

System.NullReferenceException: Object reference not set to an instance of an object.

```
   at XSharp.Project.VsTextViewCreationListener.IsOurSourceFile(String fileName) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\VsTextViewCreationListener.cs:line 149

   at XSharp.Project.VsTextViewCreationListener.VsTextViewCreated(IVsTextView textViewAdapter) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\VsTextViewCreationListener.cs:line 70

   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.&lt;&gt;c__DisplayClass432_0.&lt;InstantiateVSTextViewCreationListenere&gt;b__0()

   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
   --- End of stack trace from previous location where exception was thrown ---

   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
```

**Comment by RobertvanderHulst** [comment]
This problem occurs in the code that determines if the PRG file is part of a Vulcan project or X# project. I have already checked in a change yesterday that:
1) when the VS version is > VS 2015 then we always take ownership of PRG files (Vulcan does not support VS 2017 and VS 2019)
2) I added an extra check to avoid this problem.

Btw: most likely this problem occurred for a PRG file that was opened outside of a project.
