### ISSUE TITLE
Problem reading empty DATE fields

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#248]
The attached dbf file is one created from VO and can be opened fine from VO and DBF tools. When trying to read an empty DATE field from it, the exception below is thrown. Test app:

```
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "c:\...\testdates"
	DbUseArea(,,cDbf,,TRUE)
	DbGoTop()
	DbSkip()
	? FieldGet(7) // filled date field, ok
	DbSkip(-1)  // goto record with empty date
	? FieldGet(7) // exception
	DbCloseArea()
RETURN
```

Unhandled Exception: XSharp.Error: Input string was not in a correct format. ---
> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffe
r& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo in
fo)
   at XSharp.RDD.DbfDateColumn.GetValue(Byte[] buffer)
   at XSharp.RDD.DBF.GetValue(Int32 nFldPos)
   at XSharp.RDD.DBFDBT.GetValue(Int32 nFldPos)
   at XSharp.CoreDb.FieldGet(UInt32 nPos, Object& oRet)
   --- End of inner exception stack trace ---
   at XSharp.RT.Functions.DoError(String cSymFunc, Int32 nTries) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 246
   at XSharp.RT.Functions._DbThrowErrorOnFailure(String funcName, Boolean resultToCheck) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 19
   at XSharp.RT.Functions.FieldGet(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg:line 627
   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg:line 9

[TestDates.zip](https://github.com/X-Sharp/XSharpPublic/files/3779523/TestDates.zip)

**Comment by cpyrgas** [comment]
OK that's an impressive coincidence, I found the above problem accidentally an hour ago while investigating some different report (the RP2 problem), but just now got another report, which is due to exactly this same problem here. Here is another dbf file which shows the same problem with empty date fields:

[AGENDA.zip](https://github.com/X-Sharp/XSharpPublic/files/3779674/AGENDA.zip)
