### ISSUE TITLE
Compiler error XS9999

### ISSUE THREAD

**Issue by FrankMaraite** [X-Sharp/XSharpPublic#268]
[Issue_20191123.zip](https://github.com/X-Sharp/XSharpPublic/files/3882581/Issue_20191123.zip)

**Describe the bug**

error XS9999: An internal compiler error has occurred

**To Reproduce**

First compile the IndipendentInterfaces.viaf
then compile MSM_DbServer4DB.viaef

I get
error XS9999: An internal compiler error has occurred: 'Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.',    bei LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.PropertyContext.get_Name() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpParserCode.cs:Zeile 532.	1,1	DBServer4DB.prg	MSM_DbServer4DB

and

Compilation failed (2 errors)
error XS9999: An internal compiler error has occurred: 'Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.',    bei LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.PropertyContext.get_Name() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpParserCode.cs:Zeile 532.	1,1	DBServer4DB.prg	MSM_DbServer4DB

error XS9999: An internal compiler error has occurred: 'Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.',    bei LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.PropertyContext.get_Name() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpParserCode.cs:Zeile 532.	1,1	DBFRecord.prg	MSM_DbServer4DB

**Expected behavior**
A smooth compiler run

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 1909
 - Browser Firefox 70.0.1

**Smartphone (please complete the following information):**
 - XSharp 2.0.8.1 (Release)

**Additional context**
No

**Comment by cpyrgas** [comment]
Thanks Frank, problem has to do with the __ENTITY__ macro when used inside indexers. As a temp workaround until this is fixed, you can comment out the lines of code that use __ENTITY__, inside your PROPERTY SELF[] code.

Repro sample:

```
// error XS9999: An internal compiler error has occurred
CLASS TestClass
	PROPERTY SELF[n AS INT] AS INT
		GET
			? __ENTITY__
			RETURN 1
		END GET
		SET
			? __ENTITY__
		END SET
	END PROPERTY
END CLASS
```


```
 error XS9999: An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.PropertyContext.get_Name() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpParserCode.cs:line 558
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationCore.GetNestedName(IRuleNode ctx) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpTreeTransformationCore.cs:line 321
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationCore.GetEntityName(Boolean Full, Boolean funcNameOnly) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpTreeTransformationCore.cs:line 352
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationCore.ExitLiteralValue(LiteralValueContext context) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpTreeTransformationCore.cs:line 8038
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.LiteralValueContext.ExitRule(IParseTreeListener listener) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Generated\XSharpParser.cs:line 18891
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Antlr4.Runtime\Tree\ParseTreeWalker.cs:line 95
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Antlr4.Runtime\Tree\ParseTreeWalker.cs:line 54
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore() in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpLanguageParser.cs:line 394
```

**Comment by FrankMaraite** [comment]
Thanks a lot!

**Comment by cpyrgas** [comment]
You're welcome :)

**Comment by FrankMaraite** [comment]
Confirmed!
