### ISSUE TITLE
RP2 Problem printing custom reports

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#320]
Following code in VO works fine and shows a Preview window of the report, with a line drawn in it.

In the X# version, an error is reported "The following error was encountered while reporting: Invalid Print Preview Object".

By deleting the PrintSetPage(), the error is not thrown anymore, but the preview window is shown empty.

```
[STAThread];
FUNCTION Start() AS VOID
	LOCAL oMainWindow AS ShellWindow
	LOCAL oReport AS MyReport
	LOCAL oApp AS App

	oApp := App{}
	oMainWindow := ShellWindow{oApp}
	oMainWindow:Show(SHOWCENTERED)
	
	oReport := MyReport{oMainWindow}
	oReport:oRpPrinter:PrintPreview("aa","","abc","test",TRUE)

	oApp:Exec()
RETURN

CLASS MyReport
EXPORT oRpPrinter AS RpPrinter

CONSTRUCTOR(oShell) 
SELF:oRpPrinter := RpPrinter{oShell,SELF}

METHOD PrintPageBody(oDevice, lPrint)
	oDevice:DrawLine(0,0,200,200)
RETURN PRINT_NOMORE

METHOD PrintSetPage(oPtrDevice,nNextPageNo) 
RETURN 1

END CLASS


The following error was encountered while reporting: 

Invalid Print Preview Object: 
Parameter count mismatch.
CallStack: 
FUNCTIONS:START (12)
 (0)
 (0)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ReportPro2.RpReportOwner.PrintSetPage(PtrDevice oPrinter, Int32 nPage) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\ReportOwner.prg:line 111
   at ReportPro2.PtrDevice.CallPrintSetPage(Int32 nPageNo) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDev (R,S,D).prg:line 2342
   at ReportPro2.RpPrinter.CallPrintSetPage(Int32 nPageNo) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\RpPrinter (D).prg:line 319
   at ReportPro2.PtrDevice._CollectPreviewPage() in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDev (R,S,D).prg:line 470
   at ReportPro2.PtrDevice._GetPrintMetaPage(PrintMetaPage oResult) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDev (R,S,D).prg:line 217
   at ReportPro2.rpPrintPreviewDlg.GetMetaPage(Int32 _nPage) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDevPreview DLG - Code (R,S,D).prg:line 377
   at ReportPro2.rpPrintPreviewDlg.Dispatch(__Usual[] Xs$Args) in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDevPreview DLG - Code (R,S,D).prg:line 292
   at VOGUIClasses.Functions.__WCDialogProc(Void* hWnd, UInt32 uMsg, UInt32 wParam, Int32 lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageA(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.DoEvents()
   at ReportPro2.rpPrintPreviewDlg.EnsureModalPreview() in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDevPreview DLG - Code (R,S,D).prg:line 333
```

**Comment by cpyrgas** [comment]
Fixed
