### ISSUE TITLE
Runtime exception with subtracting DWORD from DATE

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#356]
Following results to

Unhandled Exception: System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at XSharp.__Date.op_Subtraction(__Date lhs, UInt32 days)
   at xRuntime.Exe.Functions.Start() in test.prg:line 7

```
FUNCTION Start() AS VOID
	LOCAL dDate AS DATE
	LOCAL d AS DWORD
	d := 1
	dDate := Today() + d // ok
	dDate := Today() + Day(2020.10.10) // ok
	dDate := Today() - d // exception
	dDate := Today() - Day(2020.10.10) // exception
RETURN 
```

**Comment by cpyrgas** [comment]
Problem was introduced in 2.3b and happens because of a compiler change to resolving DWORD/INT64 etc overloads. It's this code in the runtime (which has remain unchanged):


```
METHOD Subtract(days AS DWORD) AS DATE
	RETURN SELF:Add(-days)

METHOD Add(days AS DWORD) AS DATE
	VAR res := SELF:Value:AddDays(days)
	RETURN DATE{res}
METHOD Add(days AS INT64) AS DATE
	VAR res := SELF:Value:AddDays(days)
	RETURN DATE{res}
```

In builds < 2.3b, the compiler would resolve the SELF:Add() call in Subtract() to the INT64 overload, and it would work at runtime. But in 2.3b, it now resolves the call to the DWORD overload, which in our case receives a parameter value of MaxDword (-1) and throws an exception when it tries to pass this to DateTime:AddDays()

Effectively the problem(?) is the different behavior in the following code:

In build 2.3a and earlier:
INT64, -1

in build 2.3b:
DWORD, 4294967295


```
FUNCTION Start() AS VOID
	LOCAL d AS DWORD
	d := 1
	Test(-d)
RETURN 

FUNCTION Test(n AS DWORD) AS VOID
? "DWORD", n
FUNCTION Test(n AS INT64) AS VOID
? "INT64", n

```

**Comment by cpyrgas** [comment]
Fixed, by adding code to make sure DWORD is converted to INT64. Opened ticket https://github.com/X-Sharp/XSharpPublic/issues/357 for consideration.
