### ISSUE TITLE
VS Editor exception

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#364]
Type the following in the editor:

LOCAL somevalue AS OBJECT
VAR errors := someValue:ToString():TrimEnd(<CHAR>{0x0F, 0x0D})

Now put the cursor between the "{" and the "0" and type an opening paren (the reason for this is to change it to "(Char)0x0F"). The moment you type the paren, the following exception happens:

(problem is an old one actually, but still happens with the 2.3c test build)

```
  <entry>
    <record>908</record>
    <time>2020/04/19 09:26:44.261</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at XSharpModel.SystemTypeController.FindType(String typeName, IList`1 usings, IList`1 assemblies) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\MetaData\SystemTypeController.prg:line 75
   at XSharpModel.XProject.FindSystemType(String name, IList`1 usings) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\ProjectSystem\XProject.prg:line 552
   at XSharpModel.CompletionType.CheckSystemType(String typeName, IList`1 usings) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\CompletionType.prg:line 122
   at XSharpModel.CompletionType.CheckType(String typeName, XFile xFile, IList`1 usings) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\CompletionType.prg:line 147
   at XSharpModel.CompletionType.CheckType(String typeName, XFile xFile, String defaultNS) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\CompletionType.prg:line 175
   at XSharpModel.CompletionType..ctor(String typeName, XFile xFile, String defaultNS) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\CompletionType.prg:line 98
   at XSharpLanguage.XSharpTokenTools.SearchType(XFile xFile, String currentToken, CompletionElement&amp; foundElement, String currentNs) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\XSharpCompletionSource.cs:line 3252
   at XSharpLanguage.XSharpTokenTools.RetrieveType(XFile file, List`1 tokenList, XTypeMember currentMember, String currentNS, IToken stopToken, CompletionElement&amp; foundElement, ITextSnapshot snapshot, Int32 currentLine, XSharpDialect dialect) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\XSharpCompletionSource.cs:line 3142
   at XSharp.Project.CommandFilter.StartSignatureSession(Boolean comma, CompletionType cType, String methodName) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\CommandFilter.cs:line 1204
   at XSharp.Project.CommandFilter.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\CommandFilter.cs:line 673
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

```

**Comment by RobertvanderHulst** [comment]
Chris,
- Which references does the project have ?
- Which USING statements did you have at the start of the file ?

**Comment by cpyrgas** [comment]
It was a standard GUI test app that I tried it at, with the standard VOGUI references. Dialect was VO. The exact source code is:


```
[STAThread];
FUNCTION Start() AS INT
	LOCAL oXApp AS XApp
	LOCAL somevalue AS OBJECT
	
	VAR errors := someValue:ToString():TrimEnd(<CHAR>{0x0F, 0x0D})
	TRY
		oXApp := XApp{}
		oXApp:Start()
	CATCH oException AS Exception
		ErrorDialog(oException)
	END TRY
RETURN 0

CLASS XApp INHERIT App
METHOD Initialize() 

#IFDEF __APPWIZ__MODSPLASHSCREEN
  SplashScreen{SELF}:Show()
#ENDIF

  // add your application initialization code here

RETURN SELF
	

METHOD Start() 
	LOCAL oMainWindow AS StandardSDIWindow

  	SELF:Initialize()

	oMainWindow := StandardSDIWindow{SELF}
	oMainWindow:Show(SHOWCENTERED)

	SELF:Exec()
	
RETURN SELF	


END CLASS

```

**Comment by RobertvanderHulst** [comment]
Ok, Got it, found it and fixed it. The problem is not the typing of the '(' but the hovering of the mouse about the '>' character before it.

**Comment by RobertvanderHulst** [comment]
Or more precisely, not the hovering, but it tried to determine the type on that position in the line and fails to parse <CHAR> correctly
