### ISSUE TITLE
A few problems with the COPY TO command

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#478]
Put the attached dbf to C:\test and run the following code:

```
#include "dbcmd.xh"
FUNCTION Start() AS VOID
SetDefault("c:\test")
DbUseArea(,,"deallist.dbf")
COPY TO newfile
DbCloseArea()
```

1. The new dbf file does get created correctly, but it is created in the current "OS" folder, not in the folder specified by SetDefault(). Both VO and FoxPro do create the file in the SetDefault() folder

2. Try using 

COPY TO newfile CSV

this reports a compiler error, as this #command has not been defined

3. Try using either of

COPY TO newfile SDF
COPY TO newfile DELIMITED 

this does compile, but throws a runtime error when outputing the data:

```
Unhandled Exception: System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at XSharp.RDD.TEXTRDD._getFieldString(RddFieldInfo oField, Object oValue)
   at XSharp.RDD.DELIM._writeRecord()
   at XSharp.RDD.TEXTRDD.GoCold()
   at XSharp.RDD.TEXTRDD.Append(Boolean lReleaseLock)
   at XSharp.RDD.Workarea.TransRec(DbTransInfo info)
   at XSharp.RDD.DBF.TransRec(DbTransInfo info)
   at XSharp.RDD.Workarea.Trans(DbTransInfo info)
   at XSharp.RDD.DBF.Trans(DbTransInfo info)
   at XSharp.CoreDb.<>c__DisplayClass107_0.<Trans>b__0()
   at XSharp.CoreDb.Do[T](Func`1 action)
   at XSharp.CoreDb.Trans(UInt32 nDest, _FieldNames fldNames, ICodeblock uCobFor, ICodeblock uCobWhile, Object nNext, Object nRecno, Boolean lRest)
   at XSharp.RT.Functions.DbTrans(__Usual[] Xs$Args)
   at XSharp.RT.Functions.DbCopyDelim(__Usual[] Xs$Args)
```

[deallist.zip](https://github.com/X-Sharp/XSharpPublic/files/5103955/deallist.zip)

**Comment by RobertvanderHulst** [comment]
- Implemented COPY TO CSV.
- Implemented LIKE and EXCEPT clauses
- Implemented APPEND FROM in various options
- Implemented COPY TO ARRAY and APPEND FROM ARRAY
