### ISSUE TITLE
Problem with generating code in VO windows in sub folders

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#486]
https://www.xsharp.info/forum/private-product/2138-vo-code-move-to-folder-formeditor-crash

In the attached project, try generating any code (double click on the button, or generate any callback method from the Properties window), this causes VS to crash and the error found in the event log is as shown below. The WriteCallback method is the one defined in the XSharpVoEditors dll. By modifying the project a bit with some dummy changes, the error usually goes away, but it is always reproducible with the attached state of it.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at XSharp.VOEditors.XSharp_VOWindowEditor.WriteCallback(XSharp.VODesigners.DesignWindowItem, System.String)
   at XSharp.VODesigners.VOWindowEditor.ControlMouseDoubleClick(XSharp.VODesigners.DesignWindowItem, System.Windows.Forms.MouseButtons, System.Drawing.Point)
   at XSharp.VODesigners.WindowDesignerBase.HandleWndProc(XSharp.VODesigners.DesignWindowItem, System.Windows.Forms.Message ByRef)
   at XSharp.VODesigners.DesignPushButton.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
```

[NewFolder1.zip](https://github.com/X-Sharp/XSharpPublic/files/5180059/NewFolder1.zip)

**Comment by RobertvanderHulst** [comment]
The problem that the attached example shows is that opening a project without solution confuses the codemodel and can cause several exceptions, causing VS to abort.

Once you close the project in VS and when ask by VS allow it to create a solution. then close VS and open the solution then there is no problem opening the source code editor for the button click event handler (at least not on my machine with the current build).

I suspect that this is not the original problem the customer reported....

**Comment by cpyrgas** [comment]
I was afraid this could be the case. Will ask for another sample.

**Comment by RobertvanderHulst** [comment]
Fixed in next build.
