### ISSUE TITLE
Crash Visual Studio after upgrade XSharp to 2.6.1

### ISSUE THREAD

**Issue by ochristiaanse** [X-Sharp/XSharpPublic#509]
**Describe the bug**
After upgrade to XSharp 2.6.1 on opening a solution Visual studio crashes.
I used the default settings at installation.

The event viewer shows:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at XSharp.Project.XSharpProjectNode.OnProjectWalkComplete(XSharpModel.XProject)
   at XSharpModel.XProject+OnProjectWalkComplete.Invoke(XSharpModel.XProject)
   at XSharpModel.ModelWalker.Walker()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Desktop (please complete the following information):**
- windows 10
- VS 2019 latest pack

**Additional context**
The sourcecode of the solution can be supplied under NDA.

**Comment by RobertvanderHulst** [comment]
Otto,
Yes, I would like to have the source code.
And I have already a contract with your company which includes an NDA.

**Comment by RobertvanderHulst** [comment]
Otto,
It took a while but I have found the reason why it crashes:
one of the projects (_FW250_FrameworkClassesTests) is not loaded correctly and the code in our VS integration does not check correctly for this. If you remove the project from the solution then the solution loads fine.
To remove the project open the sln file with a text editor and delete the lines 83 and 84:

```
Project("{AA6C8D78-22FF-423A-9C7C-5F2393824E04}") = "_FW250_FrameworkClassesTests", "Tests\_FW250_FrameworkClassesTests\_FW250_FrameworkClassesTests.xsproj", "{43F29117-D562-4621-AAE7-7268E6615398}"
EndProject

```
After that the solution no longer crashes VS.
I'll try to find what's so special about this project (apart from the fact that it is a so called Flavored project (it has a special guid to mark it as a Microsoft Test project).

Robert
