### ISSUE TITLE
Internal compiler error with Default(USUAL) used as argument

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#664]
Following code results to an internal compiler error XS9999:

```
FUNCTION Start() AS VOID
LOCAL cb AS CODEBLOCK
cb := {|a| IsNil(a)}
? Eval(cb, NIL)
? Eval(cb, NIL , NIL , NIL)
? Eval(cb, Default(USUAL))
? Eval(cb, Default(USUAL),Default(USUAL))  // internal compiler error
? Eval(cb, Default(USUAL),Default(USUAL),Default(USUAL))  // internal compiler error


CLASS OriginalReport
METHOD Eval(cbBlock AS USUAL) AS USUAL STRICT
RETURN Eval(cbBlock,Default(USUAL),Default(USUAL),Default(USUAL))

METHOD Eval(cbBlock AS USUAL, cbForBlock AS USUAL, cbWhileBlock AS USUAL, uScope AS USUAL) AS USUAL STRICT
RETURN Default(USUAL)   
END CLASS


error XS9999: An internal compiler error has occurred: 'Index was outside the bounds of the array.',    at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.BuildStoresToTemps(Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1 parameters, ImmutableArray`1 argumentRefKinds, ImmutableArray`1 rewrittenArguments, Boolean forceLambdaSpilling, BoundExpression[] arguments, ArrayBuilder`1 refKinds, ArrayBuilder`1 storesToTemps)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.MakeArguments(SyntaxNode syntax, ImmutableArray`1 rewrittenArguments, Symbol methodOrIndexer, Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1& argumentRefKindsOpt, ImmutableArray`1& temps, Boolean invokedAsExtensionMethod, ThreeState enableCallerInfo)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.MakeCall(SyntaxNode syntax, BoundExpression rewrittenReceiver, MethodSymbol method, ImmutableArray`1 rewrittenArguments, ImmutableArray`1 argumentRefKindsOpt, Boolean expanded, Boolean invokedAsExtensionMethod, ImmutableArray`1 argsToParamsOpt, LookupResultKind resultKind, TypeSymbol type, BoundCall nodeOpt)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitCall(BoundCall node)
   at LanguageService.CodeAnalysis.XSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriter.VisitSequence(BoundSequence node)
   at LanguageService.CodeAnalysis.XSharp.BoundSequence.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.XsAddNILParameters(BoundCall node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.XsVisitCall(BoundCall node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitCall(BoundCall node)
   at LanguageService.CodeAnalysis.XSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriter.VisitList[T](ImmutableArray`1 list)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitCall(BoundCall node)
   at LanguageService.CodeAnalysis.XSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitExpression(BoundExpression node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitUnusedExpression(BoundExpression expression)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.RewriteExpressionStatement(BoundExpressionStatement node, Boolean suppressInstrumentation)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitExpressionStatement(BoundExpressionStatement node)
   at LanguageService.CodeAnalysis.XSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatement(BoundStatement node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitPossibleUsingDeclaration(BoundStatement node, ImmutableArray`1 statements, Int32 statementIndex, Boolean& replacedLocalDeclarations)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatementSubList(ArrayBuilder`1 builder, ImmutableArray`1 statements, Int32 startIndex)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitBlock(BoundBlock node)
   at LanguageService.CodeAnalysis.XSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatement(BoundStatement node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitPossibleUsingDeclaration(BoundStatement node, ImmutableArray`1 statements, Int32 statementIndex, Boolean& replacedLocalDeclarations)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatementSubList(ArrayBuilder`1 builder, ImmutableArray`1 statements, Int32 startIndex)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitBlock(BoundBlock node)
   at LanguageService.CodeAnalysis.XSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.Visit(BoundNode node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitTryStatement(BoundTryStatement node)
   at LanguageService.CodeAnalysis.XSharp.BoundTryStatement.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatement(BoundStatement node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitPossibleUsingDeclaration(BoundStatement node, ImmutableArray`1 statements, Int32 statementIndex, Boolean& replacedLocalDeclarations)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatementSubList(ArrayBuilder`1 builder, ImmutableArray`1 statements, Int32 startIndex)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitBlock(BoundBlock node)
   at LanguageService.CodeAnalysis.XSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.VisitStatement(BoundStatement node)
   at LanguageService.CodeAnalysis.XSharp.LocalRewriter.Rewrite(XSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, Boolean instrumentForDynamicAnalysis, ImmutableArray`1& dynamicAnalysisSpans, DebugDocumentProvider debugDocumentProvider, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawLocalFunctions, Boolean& sawAwaitInExceptionHandler)
   at LanguageService.CodeAnalysis.XSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
   at LanguageService.CodeAnalysis.XSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)

```

**Comment by cpyrgas** [comment]
Confirmed fixed.
