### ISSUE TITLE
VS Editor exception

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#674]
Got the following while I was trying to delete a property, It was:

   PROPERTY oConn AS AdoConnection
      GET
         RETURN MDVNGlobalSettings.oConn
      END GET
   END PROPERTY

I first deleted the 1st line, then tried to delete the rest, in the meantime got the exception

```

System.NullReferenceException: Object reference not set to an instance of an object.
at XSharpModel.XSourceMemberSymbol.get_ComboPrototype() in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\Source\XSourceMemberSymbol.prg:line 113
at XSharp.LanguageService.XSharpDropDownClient.loadMemberCombos(Int32 selectedType, Int32 nLine) in C:\XSharp\DevPublic\VisualStudio\LanguageService\NavigationBar\DropDownClient.cs:line 440
at XSharp.LanguageService.XSharpDropDownClient.reloadCombos(Int32 nLine) in C:\XSharp\DevPublic\VisualStudio\LanguageService\NavigationBar\DropDownClient.cs:line 487
at XSharp.LanguageService.XSharpDropDownClient.SelectContainingMember(Int32 newLine) in C:\XSharp\DevPublic\VisualStudio\LanguageService\NavigationBar\DropDownClient.cs:line 247
at XSharp.LanguageService.XSharpDropDownClient.Caret_PositionChanged(Object sender, CaretPositionChangedEventArgs e) in C:\XSharp\DevPublic\VisualStudio\LanguageService\NavigationBar\DropDownClient.cs:line 143
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) --- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by cpyrgas** [comment]
Confirmed fixed.
