### ISSUE TITLE
VS2017 freeze and editor exception with incomplete code

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#751]
The attached solution contains a .prg with incomplete code (tests for various reported issues):

[ConsoleApplication9.zip](https://github.com/X-Sharp/XSharpPublic/files/6925909/ConsoleApplication9.zip)

1. Open the .prg file and Save, VS 2017 will freeze
2. Open it again, and type an opening parenthesis anywhere in the code, an exception occurs:

```
System.ArgumentNullException: Value cannot be null. Parameter name: source
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
at XSharp.LanguageService.XSharpSignatureHelpCommandHandler.findElementAt(Boolean comma, SnapshotPoint ssp, XSharpSearchLocation location) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Parameter Info\SignatureCommandHandler.cs:line 255
at XSharp.LanguageService.XSharpSignatureHelpCommandHandler.StartSignatureSession(Boolean comma, IXTypeSymbol type, String methodName, Char triggerchar) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Parameter Info\SignatureCommandHandler.cs:line 284
at XSharp.LanguageService.XSharpSignatureHelpCommandHandler.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Parameter Info\SignatureCommandHandler.cs:line 136
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at XSharp.LanguageService.CommandFilter.<>c__DisplayClass13_0.<<Exec>b__1>d.MoveNext() in C:\XSharp\DevPublic\VisualStudio\LanguageService\CommandFilter.cs:line 112 --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at XSharp.LanguageService.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\XSharp\DevPublic\VisualStudio\LanguageService\CommandFilter.cs:line 108
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) 
```

**Comment by cpyrgas** [comment]
Confirmed fixed
