### ISSUE TITLE
Internal Compiler Error with multiple PRIVATE &varName commands

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#780]
Following code throws an error XS9999: An internal compiler error has occurred because of the multiple PRIVATE &cVarName declarations:

```

FUNCTION Start() AS VOID
	LOCAL cVarName AS STRING
	
	IF TRUE
	   cVarName := "myPrivate"
		PRIVATE &cVarName
		&cVarName := 1
		? &cVarName
	ENDIF
	IF TRUE
		PRIVATE &cVarName
		? &cVarName
		cVarName := "newtest"
		&cVarName := 2
		? &cVarName
		
		cVarName := "myPrivate"
		? &cVarName
	ENDIF
	
RETURN

error XS9999: An internal compiler error has occurred: 'An item with the same key has already been added.',    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.EntityData.AddField(String Name, String Alias, XSharpParserRuleContext context)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.addFieldOrMemvar(String name, String prefix, XSharpParserRuleContext context, Boolean isParameter)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.AddAmpbasedMemvar(XSharpParserRuleContext context, String name, String alias, IToken amp)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.EnterXbasedecl(XbasedeclContext context)
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.XbasedeclContext.EnterRule(IParseTreeListener listener)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore()

```

**Comment by cpyrgas** [comment]
Confirmed fixed
