### ISSUE TITLE
DbEval in FoxPro with VOID function causes an error

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#890]
Also, taken from C795:

in VFP dialect only:

(although this could actually be due to https://github.com/X-Sharp/XSharpPublic/issues/886)
```
FUNCTION Start() AS VOID
LOCAL cFileName AS STRING
cFileName := "testvfp"
DbCreate(cFileName , {{"FLD","N",5,0}})
DbUseArea(,,cFileName)
DbAppend()
DbAppend()
DbGoTop()

DbEval({|| EvalFunc( RecNo())} )

FUNCTION EvalFunc(n AS DWORD) AS VOID
? n

```

this results to a dialog:

```

---------------------------
ERROR
---------------------------
Description :	Unknown Error occurred

Subsystem :	BASE

GenCode :	EG_EXCEPTION Exception raised by CLR or external code

FuncSym :	DbEval

Severity :	ES_ERROR

Can Default :	False

Can Retry :	False

Can Substitute :	False

Stack Trace :	

   at XSharp.RT.Functions._DbThrowErrorOnFailure(String funcName, Boolean resultToCheck)

   at XSharp.RT.Functions.DbEval(__Usual[] Xs$Args)

   at fox.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\fox\Prg\fox.prg:line 13




---------------------------
Abort   Retry   Ignore   
---------------------------

```

_Originally posted by @cpyrgas in https://github.com/X-Sharp/XSharpPublic/issues/585#issuecomment-991342061_

**Comment by cpyrgas** [comment]
Confirmed fixed
