### ISSUE TITLE
Transporter / Compiler problem with delegate

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#932]
Hi Robert,

In VO I have the following function:
FUNCTION Anrede(cDB,cPrimKey,nOrder,cAnschrTyp,lPartner,lVorname)

In addition somewhere else in the code I have the following line:
nPos := At("@ANREDE",Upper(cTxt))

Because of this the transporter seems to produce the follwing lines:
DELEGATE Anrede_delegate(cDB,cPrimKey,nOrder,cAnschrTyp,lPartner,lVorname)
FUNCTION Anrede(cDB,cPrimKey,nOrder,cAnschrTyp,lPartner,lVorname)

With this wrong delegate the compiler (2.10) crashes with

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	XS9999	An internal compiler error has occurred: 'Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.',    bei LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT._getParameterType(ParameterContext context)	04-proMOCore	D:\Projekte\proMO\04-proMOCore\_App\_Makrofunktionen.prg	1	

The cause of the crash was rather difficult to find...
In 2.09 the compiler did not crash.

Karl

**Comment by cpyrgas** [comment]
Robert (and Karl), I will fix this in the VOXporter, but there's also a compiler bug, as the above sample shows, this causes the compiler to crash (in the latest build):


```
DELEGATE test_delegate(a,b)

error XS9999: An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT._getParameterType(ParameterContext context)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationCore.ExitParameter(ParameterContext context)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.ExitParameter(ParameterContext context)
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.ParameterContext.ExitRule(IParseTreeListener listener)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore()
```

**Comment by RobertvanderHulst** [comment]
Chris,
(Co) assign this to me then.

**Comment by cpyrgas** [comment]
Confirmed fixed
