### ISSUE TITLE
ArgumentNullException in Output-Window for extension

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#940]
From time to time I see the following exception in the output Window (Show output from is set to "Extension").

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: textView
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetVsTextViewFromTextView(ITextView textView)
   at Microsoft.VisualStudio.TextManager.Interop.IVsTextViewExtensions.<ToIVsTextViewAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XSharp.Project.XSharpShellLink.<OpenDocumentAsync>d__21.MoveNext() in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 167
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: textView
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetVsTextViewFromTextView(ITextView textView)
   at Microsoft.VisualStudio.TextManager.Interop.IVsTextViewExtensions.<ToIVsTextViewAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XSharp.Project.XSharpShellLink.<OpenDocumentAsync>d__21.MoveNext() in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 167<---
```

There is no output in the log files

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
This error seems to indicate that the projectsystem tried to open a file that no longer exists. Could that be the case ?
Anyway, I have added a null check to avoid this error.

**Comment by hpetriffer** [comment]
It is possible. But I'm not sure. I got it a few times, also after restarting Visual Studio (but I don't know anymore what I have done).

**Comment by cpyrgas** [comment]
Can't confirm or unconfirm this one, will leave it up to Hansjoerg
