### ISSUE TITLE
Reading type info from C# SDK type project fails

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#950]
When a X# project has a reference to a C# SDK style project then the code that tries to get the filename from the project fails.
See the log from HansJoerg.
Apparently the project cannot be casted to a EnvDTE.Project

```
2022-01-21 07:35:05.134 +01:00 [ERR] 0001 Goto failed
System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' to type 'EnvDTE.Project'.
   at XSharpModel.XProject.RefreshStrangerProjectDLLOutputFiles_Worker() in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\ProjectSystem\XProject.prg:line 538
   at XSharp.Project.XSharpProjectNode.<>c__DisplayClass110_0.<<RunInForeGroundThread>b__0>d.MoveNext() in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Nodes\XSharpProjectNode.cs:line 1538
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at XSharp.Project.XSharpProjectNode.RunInForeGroundThread(Action a) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Nodes\XSharpProjectNode.cs:line 1540
   at XSharpModel.XProject.RefreshStrangerProjectDLLOutputFiles() in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\ProjectSystem\XProject.prg:line 565
   at XSharpModel.XProject.FindSystemType(String name, IList`1 usings) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\ProjectSystem\XProject.prg:line 866
   at XSharpModel.XProject.FindType(String typeName, IList`1 usings) in C:\XSharp\DevPublic\VisualStudio\XSharpCodeModelXs\ProjectSystem\XProject.prg:line 948
   at XSharp.LanguageService.XSharpLookup.SearchType(XSharpSearchLocation location, String name) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Lookup\XSharpLookup.cs:line 1362
   at XSharp.LanguageService.XSharpLookup.GetTypeFromSymbol(XSharpSearchLocation location, IXSymbol symbol) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Lookup\XSharpLookup.cs:line 250
   at XSharp.LanguageService.XSharpLookup.RetrieveElement(XSharpSearchLocation location, IList`1 xtokenList, CompletionState state, String& notProcessed, Boolean forQuickinfo) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Lookup\XSharpLookup.cs:line 553
   at XSharp.LanguageService.XSharpGotoDefinition.GotoDefn(ITextView TextView) in C:\XSharp\DevPublic\VisualStudio\LanguageService\Generic\GotoDefinition.cs:line 45
```

**Comment by cpyrgas** [comment]
Robert, I will take your word on this and confirm it :)
